version: "3"

env:
  PORT: "8000"

tasks:
  build:binary:
    desc: "Build the server binary"
    cmds:
      - if [ "$(go env GOOS)" = "windows" ]; then
        go build -o bin/server.exe cmd/uno/*.go;
        else
        go build -o bin/server cmd/uno/*.go;
        fi

  build:image:
    desc: "Build the Docker Image from the Binary"
    cmds:
      - docker buildx create --use
      - docker buildx build --platform linux/amd64,linux/arm64 -t uno-server:latest .
    deps:
      - build:binary

  run:server:
    desc: "Run the server"
    cmds:
      - if [ "$(go env GOOS)" = "windows" ]; then
        bin/server.exe;
        else
        bin/server;
        fi
    deps:
      - build:binary

  debug:
    desc: "Run the server in debug mode"
    cmds:
      - if [ "$(go env GOOS)" = "windows" ]; then
        dlv exec bin/server.exe --headless --listen=:2345 --api-version=2;
        else
        dlv exec bin/server --headless --listen=:2345 --api-version=2;
        fi
    deps:
      - build:binary
